name: docker-publish-to-dh

# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags
on:
  push:
    tags:
    - "**"
    branches:
    - "v*.*.**"
    - "master"

jobs:
  docker-publish-to-dh:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/actions/checkout
    - name: Checkout
      uses: actions/checkout@v2

    # https://github.com/docker/build-push-action
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: rammusxu/${{ github.event.repository.name }}
        tag_with_ref: true
        tag_with_sha: true
